version: '3.8'
services:
    python-flask:
        container_name: vsnippet-cache-poisoning-classic-27
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:1337
